package com.trainingsplan.entity;

public enum AuditAction {
    // Auth
    LOGIN, PASSWORD_CHANGED, EMAIL_VERIFIED,
    // Admin
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_STATUS_CHANGED, SUBSCRIPTION_CHANGED,
    // User
    FIT_UPLOADED, STRAVA_CONNECTED, STRAVA_DISCONNECTED, COROS_CONNECTED, COROS_DISCONNECTED,
    TRAINING_PLAN_ASSIGNED, PROFILE_UPDATED,
    // System
    PLAN_CREATED, PLAN_DELETED, COMPETITION_CREATED, COMPETITION_DELETED, COMPETITION_UNREGISTERED
}
